### ISSUE TITLE
Demo: New CodeSandbox domain not authorized

### ISSUE THREAD

**Issue by karlhorky** [donavon/use-firebase-auth#2]
Hey @donavon, thanks for the library!

On the demo, it seems like the new CodeSandbox domain (`jjjqrm6q85.csb.app`) is not authorized to use your Firebase Authentication demo account:

https://codesandbox.io/s/jjjqrm6q85?fontsize=14

![Screen Shot 2019-12-17 at 12 45 40](https://user-images.githubusercontent.com/1935696/70993090-8df03100-20cb-11ea-971d-041af31a460d.png)

**Comment by donavon** [comment]
I fixed this some time ago, but forgot to close. closing now.

**Comment by karlhorky** [comment]
Thanks! Seems to (mostly) work.

I guess GitHub doesn't load in the sandbox iframe (maybe it would be good to have a very visible message in the demo such as "open in new tab" or something):

![Screen Shot 2020-08-28 at 16 59 26](https://user-images.githubusercontent.com/1935696/91582460-24117200-e950-11ea-956d-201af7cdbae8.png)

Looks good in a standalone tab:

![Screen Shot 2020-08-28 at 16 59 34](https://user-images.githubusercontent.com/1935696/91582479-2b388000-e950-11ea-9fc9-6e1b88cea9e4.png)

**Comment by donavon** [comment]
thanks. I've confirmed that this is the case.
